apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cloudchamp
spec:
  type: NodePort
  selector:
    role: api  # Corrected to match the Deployment's matchLabels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # This should map to the container port
      nodePort: 30080  # Port in the range 30000-32767